import enum


class ParcelStatus(str, enum.Enum):
    OBSERVED = "OBSERVED"
    CANDIDATE = "CANDIDATE"
    VALIDATED = "VALIDATED"
    REVIEW = "REVIEW"
    FIELD_VERIFICATION = "FIELD_VERIFICATION"
    REJECTED = "REJECTED"
    APPROVED = "APPROVED"
    PUBLISHED = "PUBLISHED"


class ConflictType(str, enum.Enum):
    REGISTRATION_FAILURE = "REGISTRATION_FAILURE"
    GEOMETRY_INVALID = "GEOMETRY_INVALID"
    PARCEL_OVERLAP = "PARCEL_OVERLAP"
    PARCEL_GAP = "PARCEL_GAP"
    AMBIGUOUS_MATCH = "AMBIGUOUS_MATCH"
    SPLIT_AMBIGUITY = "SPLIT_AMBIGUITY"
    MERGE_AMBIGUITY = "MERGE_AMBIGUITY"
    AREA_MISMATCH = "AREA_MISMATCH"
    ATTRIBUTE_CONFLICT = "ATTRIBUTE_CONFLICT"
    IDENTITY_CONFLICT = "IDENTITY_CONFLICT"
    PHYSICAL_EVIDENCE_CONFLICT = "PHYSICAL_EVIDENCE_CONFLICT"
    LEGAL_REVIEW_REQUIRED = "LEGAL_REVIEW_REQUIRED"
    STRUCTURAL_AMBIGUITY = "STRUCTURAL_AMBIGUITY"


class MatchRelation(str, enum.Enum):
    ONE_TO_ONE = "ONE_TO_ONE"
    SPLIT = "SPLIT"
    MERGE = "MERGE"
    BOUNDARY_ADJUSTMENT = "BOUNDARY_ADJUSTMENT"
    NO_MATCH = "NO_MATCH"
    AMBIGUOUS = "AMBIGUOUS"


class ObservationType(str, enum.Enum):
    BUILDING_EDGE = "BUILDING_EDGE"
    WALL = "WALL"
    FENCE = "FENCE"
    ROAD_EDGE = "ROAD_EDGE"
    DRAIN = "DRAIN"
    SURVEY_MARK = "SURVEY_MARK"
    VISIBLE_PLOT_DIVISION = "VISIBLE_PLOT_DIVISION"
    VEGETATION_BOUNDARY = "VEGETATION_BOUNDARY"
    BUILDING = "BUILDING"
    OTHER = "OTHER"


class ReviewActionType(str, enum.Enum):
    APPROVE = "APPROVE"
    EDIT = "EDIT"
    FIELD_VERIFY = "FIELD_VERIFY"
    REJECT = "REJECT"


class ActorRole(str, enum.Enum):
    AI_SERVICE = "AI_SERVICE"
    REVIEWER = "REVIEWER"
    ADMIN = "ADMIN"
    SYSTEM = "SYSTEM"
